---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgANt4X8qnNi+xfrP9b4sq7wC/4oWRoGxf5R6vNn49402wQp60GuA1tAhGYmSvxINldz2ddKGBcZAWd3XXhEYu384YJHckd94q3OP1Y5RPZQm58S0a0TnCMhox7J8RsbB6G56J+/9RyhLM87nMBiLVKC9AwjsSyqgk20x36Kd35QvM+nExfqcrhV1YrxV2m8MfnPHfMfG+yiDf0DVldEkgAnCP5lXLX7vOFHwXPMiArVQLlXC+Ow5M2MV88EuLQscQtadxLCGbQRcFdzBCvFkpVZcx1jUge2ThAgyjxzbve9/FAm10udcstDDxldmElhkKwMw/GCksEl3T40l5DulLzNh9bDhHL/ZpVkR4+7cQFsn0OTrhTVjjrwIPkYXW9PFPYV+eseMObbSV4O7r2sVd0FAJaabthLM/6E1qwT1eVBDsS97UOu3VnxCSQC8SvQCCIVZyqoJSX5mBX5uX8L2TyVM3+STJK0j2a3FDONdI/6kHqFqsuGB23KLgso1nP5wULadE/9thmGMio2HnvfitFIU4YkX556yJJvYN7P05jk+h+0tPii27jdaJk67dAX0DpkmnpUGxjufzmeHymg15o5LH2gDh74ZCrKCqgPxzfWF47xlUZVXSVDU0ZcfzxlPy0bp0WWX/7sRk7lHzjPfcT/dyYVPKvkvKRC7thr1jrJPvxMyLdcsMhiJ5SB+CSKJp96Ug/+rpkoJCZ1JHR3jlC4eIQj
    username: AgCPLA9xbDLdkLim9XF7+abuY8jC8SA7K3Na8u++hychMEXsafuSSALkfdeo54MXNELL2DEI1qhCYetLF+gQQjtISldEvQp8K8rS09Hj6Aw7HuFUG8Onn6AsKZFdB2bPtp3zwDEMgHebLD+0vI/bVeN56/edrOvtmZ7Ovpc1E7fXspcajkHqtBsi9vkebDruPctrahzYHQHAKYE8MPWs68q3c2/FO3sSnli+idLiBDEF5mkMkySl/P4ZIOEFCr4mSLkCgUYoBsRFZANWbbiLab4bz6LF+O4BnWpYPWeQ6V0WvNTQ583v/TuNKz9SvBJ/UHDucGdRfPgXopeWUd+z793jBMG9OJTbmP3RC7t4upB9l3ktPzdSQAcEvdvWvKi+VmW46hTYM6q14hTfnBtJV6pQki/NC9n3DUKO2uLU10PIGD47S0IgboorHMG1E5/X1j9HYOx5E8mlg4/bjqbxlacbroja7V/kjkq8n4+dbCrdi7G8x4niVfSKXRrva8og+jCcXSMLtuOJBE00UYxO9MIn3n60cwutRK5QImzuY9e1TXntTngTg7/kYm2LEzURF4bmSS9ZLLXjPmIYvA4755VjxKBWDTGsTZIt/cJ0pM6PIL++30OxID9SuSeGD1A5Qca5HuAcKOADJQXAz7dOyl3Q9gNXeHTx1lxS+BYM/ZpkmWf+TrXEpGn6P7vduMxI36FQy4BRdg==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
